### ISSUE TITLE
Arabic rendering of text is broken

### ISSUE THREAD

**Issue by boulabiar** [maplibre/maplibre-gl-leaflet#13]
Thanks for this great project.

I've just noticed that Arabic words are rendered without ligature (letters not connected) and with the letters in the reverse order.

**Comment by lseelenbinder** [comment]
This is broken by default in MapLibre GL. It requires an extra plugin: https://github.com/mapbox/mapbox-gl-rtl-text (should be drop-in usable for MapLibre).
