### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by pietervdvn** [maplibre/maplibre-gl-leaflet#16]
The demo as linked in the readme gives a gray background - maybe an incompatibility with current leaflet?

We want to use this in MapComplete...

![image](https://user-images.githubusercontent.com/1466478/125616380-2babe3a6-eade-4b16-a850-6a78d45f8def.png)

**Comment by wipfli** [comment]
Hi. Thanks for reporting. Which demo is broken? The [basic demo](https://raw.githack.com/maplibre/maplibre-gl-leaflet/aa06e210ab8f8ea136407a8f1481b4b8077c3d5a/examples/basic.html) works for me.

**Comment by pietervdvn** [comment]
For me on firefox (Kubuntu) this gives the grey screen as reported above. It works on chromium however, so this seems to be FF-specific.

**Comment by webberig** [comment]
I just tested the demo on firefox, and it's working for me... Has this been resolved ?

**Comment by pietervdvn** [comment]
Seems to work now... Must have been a glitch or a script blocker.
