### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by gavinr** [maplibre/maplibre-gl-leaflet#28]
The demo links [linked from the readme](https://github.com/maplibre/maplibre-gl-leaflet/blame/main/README.md#L33-L37) are not working

- https://raw.githack.com/maplibre/maplibre-gl-leaflet/aa06e210ab8f8ea136407a8f1481b4b8077c3d5a/examples/basic.html
- https://raw.githack.com/maplibre/maplibre-gl-leaflet/aa06e210ab8f8ea136407a8f1481b4b8077c3d5a/examples/cluster.html
- https://raw.githack.com/maplibre/maplibre-gl-leaflet/aa06e210ab8f8ea136407a8f1481b4b8077c3d5a/examples/events.html

![image](https://user-images.githubusercontent.com/209355/184434870-00094fae-97a6-4515-8d75-29e858a2b776.png)

## Possible cause

It looks like the SSL cert is invalid on https://media.seventhsense.ai/maplibre-gl-js/v1.14.0/maplibre-gl.js and  https://media.seventhsense.ai/maplibre-gl-js/v1.14.0/maplibre-gl.css

## Possible solution

Can we switch those URLs to unpkg? e.g. https://unpkg.com/maplibre-gl@1.14.0/dist/maplibre-gl.js (or the latest version  https://unpkg.com/maplibre-gl@2.1.9/dist/maplibre-gl.js)

**Comment by wipfli** [comment]
Yes that would be great! Can you make a pull request?
