### ISSUE TITLE
Maplibre-gl-leaflet layer is mis-aligned with map when panning the map off screen

### ISSUE THREAD

**Issue by gavinr** [maplibre/maplibre-gl-leaflet#29]
If you drag the map out of the window, the maplibre-gl-leaflet layer gets stuck in view while other leaflet layers (like markers) continue to get pulled, causing the two layers not to be aligned correctly. 

## Replication case

https://jsbin.com/vepuyeqoyo/3/edit?html,output

1. Open the demo case
2. Drag the map down
    - **Expected**: point stays in its place relative the maplibre-gl-leaflet layer (in the ocean above greenland)
    - **Actual**: when the maplibre-gl-leaflet layer reaches the bottom of the window, as the map continues to be drug down, the point moves relative to the maplibre-gl-leaflet layer, moving all the way off screen.

https://user-images.githubusercontent.com/209355/184433968-8462d8ce-71c6-4628-96d6-02ee44dd1a67.mp4

**Comment by wipfli** [comment]
Thanks for taking the time to open this issue @gavinr

**Comment by gavinr** [comment]
Sorry, the original issue had the wrong link to the replication case - here is the corrected: https://jsbin.com/vepuyeqoyo/3/edit?html,output

**Comment by wipfli** [comment]
Is there a way to limit the map movement maybe?

**Comment by patrickarlt** [comment]
@wipfli yes Leaflet supports a `maxBounds` property and `setMaxBounds()` method on the `Map`. Enabling it seems to fix the issues:

https://jsbin.com/yofobup/1/edit?html,output

```js
var map = L.map('map', {
  maxBounds:[[-90,-180], [90,180]] // limit to the defined world bounds
}).setView([0,0 ], 2);

L.marker([179, 0])
    .bindPopup("Hello <b>Leaflet GL</b>!<br>Whoa, it works!")
    .addTo(map)
    .openPopup();

var gl = L.maplibreGL({
    // get your own MapTiler token at https://cloud.maptiler.com/ or use MapBox style
    style: 'https://api.maptiler.com/maps/topo/style.json?key=gbetYLSD5vR8MdtZ88AQ'
}).addTo(map);
```

I guess the question is do we try to just limit the north/south panning/zooming behavior in [`_update` or `_transformGl()`](https://github.com/maplibre/maplibre-gl-leaflet/blob/main/leaflet-maplibre-gl.js#L151-L196) or just call `map.setMaxBounds([[-90,-180], [90,180]])` and document this behavior.

**Comment by wipfli** [comment]
Since it is a north/south problem, I would like to avoid limiting also east/west movement, so `map.setMaxBounds([[-90,-180], [90,180]])` seems like a bad option. But could you maybe share the idea of fixing the problem with `_update` in a pull request? That would be interesting...

**Comment by patrickarlt** [comment]
@wipfli I can give it a shot but it probably won't be soon.

**Comment by patrickarlt** [comment]
@wipfli @gavinr turns out this was really simple. I put up https://github.com/maplibre/maplibre-gl-leaflet/pull/31 with a fix.
