### ISSUE TITLE
TouchPitchHandler is not active by default?

### ISSUE THREAD

**Issue by PedroVenancio** [maplibre/maplibre-gl-leaflet#46]
Hi,

Sorry, I'm new to maplibre-gl-leaflet and I'm testing it on an Android device. It seems that TouchPitchHandler is not active by default or it is not working.

For instance in the example:
https://raw.githack.com/maplibre/maplibre-gl-leaflet/main/examples/events.html
- on desktop I can rotate and tilt map with mouse right button;
- on android, I can't rotate or tilt map by dragging up and down with two fingers, as described in https://maplibre.org/maplibre-gl-js-docs/api/handlers/#touchpitchhandler 
- The double click to zoom (https://maplibre.org/maplibre-gl-js-docs/api/handlers/#doubleclickzoomhandler) seems to work.

Is this the expected behaviour with maplibre-gl-leaflet? Using pure maplibre-gl-js I can use the two fingers to tilt and rotate.

Thank you very much!

**Comment by lseelenbinder** [comment]
Hi @PedroVenancio.

I can't speak to the specific handler, but it's not possible to tile/rotate in Leaflet, so this plugin disables that entirely in maplibre (if it were enabled, the Leaflet map and the MapLibre map would be misaligned). Does that answer your question? It looks like it may be possible we need to _disable_ the right mouse-button handler as well to keep things consistent.

**Comment by PedroVenancio** [comment]
Hi @lseelenbinder 

Absolutely, it makes sense. I'm closing the issue. Thank you very much Luke.
