### ISSUE TITLE
Migrating from @codespree

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-leaflet#5]
Thank you @codespree for migrating `mapbox-gl-leaflet` to `maplibre-gl-leaflet`. As you have suggested in https://github.com/maplibre/maplibre-gl-js/issues/123 we can now continue maintaining this project in the `maplibre` organization on GitHub.

Maybe you can add a link to this repository here at the top of the `README` in your repo.

**Comment by codespree** [comment]
@wipfli I'll remove it from my org now. Thanks for maintaining it here!

Cheers!
