### ISSUE TITLE
support maplibre-gl 4.x

### ISSUE THREAD

**Issue by razor-1** [maplibre/maplibre-gl-leaflet#55]
So far everything appears to be working; if there are no known issues, could 4.x be added to the version spec? Thank you

**Comment by CyrilleTanguay** [comment]
I can't install the package, because it is incompatible with maplibre-gl 4.1.3...

**Comment by lseelenbinder** [comment]
Resolved in https://github.com/maplibre/maplibre-gl-leaflet/commit/0dc10160e353851b59a1800e3876a57bdcefcf31. 💯
