### ISSUE TITLE
Put the minified files on a CDN

### ISSUE THREAD

**Issue by codespree** [maplibre/maplibre-gl-leaflet#6]
Currently the `README.md` points to minified files hosted at the following two locations:
```
<!-- Maplibre GL -->
<link href="https://media.seventhsense.ai/maplibre-gl-js/v1.14.0/maplibre-gl.css" rel='stylesheet' />
<script src="https://media.seventhsense.ai/maplibre-gl-js/v1.14.0/maplibre-gl.js"></script>
```

I suggest that we move away from my org CDN to a publicly available CDN like https://cdnjs.com/

This will allow you to keep the files in sync with any updates in this repository.

**Comment by wipfli** [comment]
Thanks for pointing this out @codespree. Actually, I already prepared a pull request to fix this: https://github.com/maplibre/maplibre-gl-leaflet/pull/3

Would you mind reviewing this pull request and also the other two that I made?

**Comment by wipfli** [comment]
@nyurik can you add @codespree to the MapLibre Developer team such that we can work together on this repo?
