### ISSUE TITLE
Before publishing on NPM

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-leaflet#9]
What is left to do with this repo before we publish on NPM?

**Comment by wipfli** [comment]
Good idea. Can you make a pull request?

**Comment by tuukka** [comment]
In #10, I put `maplibre-gl` in peer dependencies for now. I'm unsure if something should change in the beginning of `leaflet-maplibre-gl.js`, if `maplibre-gl` changes to a direct dependency.

**Comment by wipfli** [comment]
Whose NPM access token can we use for this? @klokan @nyurik @lseelenbinder maybe yours?

**Comment by holsteinkaa** [comment]
Any news on this?

**Comment by wipfli** [comment]
@holsteinkaa thanks for the ping. Can you review https://github.com/maplibre/maplibre-gl-leaflet/pull/12?

**Comment by wipfli** [comment]
````
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@maplibre%2fmaplibre-gl-leaflet - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```
see https://github.com/maplibre/maplibre-gl-leaflet/runs/2907945845?check_suite_focus=true

@nyurik can you add me to the NPM maplibre org?

**Comment by wipfli** [comment]
It is now online as a release candidate https://www.npmjs.com/package/@maplibre/maplibre-gl-leaflet

**Comment by wipfli** [comment]
Seems to work with tag triggers too: https://github.com/maplibre/maplibre-gl-leaflet/actions/runs/1057084508
